// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEbyO59QVBF8iMFXTfUwJlcvZkA3MEYk',
    appId: '1:377443910819:web:a47886159f820cb7512b16',
    messagingSenderId: '377443910819',
    projectId: 'riverpod-flutter-course-sell',
    authDomain: 'riverpod-flutter-course-sell.firebaseapp.com',
    storageBucket: 'riverpod-flutter-course-sell.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Hynb6Fnc7j_TR0SdKTha0dk3aAdXAD8',
    appId: '1:377443910819:android:bc2e6ac5e200bf6b512b16',
    messagingSenderId: '377443910819',
    projectId: 'riverpod-flutter-course-sell',
    storageBucket: 'riverpod-flutter-course-sell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-PhIlg6NJ9-B7hM87UGx7HA2Pd8rYw2E',
    appId: '1:377443910819:ios:e570822c82a1ddd7512b16',
    messagingSenderId: '377443910819',
    projectId: 'riverpod-flutter-course-sell',
    storageBucket: 'riverpod-flutter-course-sell.appspot.com',
    iosClientId: '377443910819-uurnbnihihnubpid76jbhk2qhs511qen.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrookCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-PhIlg6NJ9-B7hM87UGx7HA2Pd8rYw2E',
    appId: '1:377443910819:ios:e49f5a88fd9af307512b16',
    messagingSenderId: '377443910819',
    projectId: 'riverpod-flutter-course-sell',
    storageBucket: 'riverpod-flutter-course-sell.appspot.com',
    iosClientId: '377443910819-0s3t371vg1726e9irkn5okhr3np2d145.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrookCourse.RunnerTests',
  );
}
